config:
  project:                measurement-lab
  dataset:                release
  email:                  speedupamerica-lanecounty-mvp@mlab-sandbox.iam.gserviceaccount.com
  private_key_path:       keys/speedupamerica-lanecounty-mvp@mlab-sandbox.iam.gserviceaccount.com.p12
  private_key_passphrase: notasecret
  auth_method:            private_key
